export const mockData = {
  clients: [
    {
      id: "1",
      name: "John Doe",
      email: "john@dummy.com",
      phone: "+1 234 567 8900",
      address: "123 Main St, New York, NY",
      caseStatus: "Active",
      avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop&crop=face",
      joinDate: "2024-01-15",
      company: "Doe Enterprises",
      notes: "High-value client with multiple ongoing cases. Prefers email communication.",
      socialMedia: {
        linkedin: "https://linkedin.com/in/johndoe",
        twitter: "https://twitter.com/johndoe",
      },
    },
    {
      id: "2",
      name: "Jane Smith",
      email: "jane@dummy.com",
      phone: "+1 234 567 8901",
      address: "456 Oak Ave, Los Angeles, CA",
      caseStatus: "Pending",
      avatar: "https://images.unsplash.com/photo-1494790108755-2616b612b786?w=150&h=150&fit=crop&crop=face",
      joinDate: "2024-02-20",
      company: "Smith & Associates",
      notes: "Family law case, sensitive matter requiring discretion.",
      socialMedia: {
        linkedin: "https://linkedin.com/in/janesmith",
      },
    },
    {
      id: "3",
      name: "Mike Wilson",
      email: "mike@dummy.com",
      phone: "+1 234 567 8902",
      address: "789 Pine St, Chicago, IL",
      caseStatus: "Closed",
      avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop&crop=face",
      joinDate: "2024-03-10",
      company: "Wilson Corp",
      notes: "Successfully resolved criminal defense case. Potential for future business.",
    },
  ],
  cases: [
    {
      id: "1",
      title: "Business Litigation Case",
      client: "John Doe",
      attorney: "Mical Lobani",
      caseType: "Business Law",
      status: "Active",
      priority: "High",
      deadline: "2024-12-31",
      description: "Complex business litigation involving contract disputes and intellectual property rights.",
      clientAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop&crop=face",
      progress: 65,
      timeline: [
        { date: "2024-01-15", event: "Case Filed", description: "Initial case filing and documentation" },
        { date: "2024-02-20", event: "Discovery Phase", description: "Evidence gathering and witness interviews" },
        { date: "2024-03-10", event: "Mediation Scheduled", description: "Mediation session scheduled for next month" },
      ],
    },
    {
      id: "2",
      title: "Family Custody Case",
      client: "Jane Smith",
      attorney: "Sarah Johnson",
      caseType: "Family Law",
      status: "Pending",
      priority: "Medium",
      deadline: "2024-11-15",
      description: "Child custody case involving divorced parents seeking joint custody arrangement.",
      clientAvatar: "https://images.unsplash.com/photo-1494790108755-2616b612b786?w=150&h=150&fit=crop&crop=face",
      progress: 30,
      timeline: [
        { date: "2024-02-01", event: "Initial Consultation", description: "First meeting with client" },
        { date: "2024-02-15", event: "Documentation Review", description: "Review of existing custody agreements" },
      ],
    },
  ],
  attorneys: [
    {
      id: "1",
      name: "Mr. Tristan",
      email: "tristan@dcase.com",
      phone: "+1 234 567 8900",
      specialization: "Estate Planning Lawyer",
      experience: 8,
      rating: 4.8,
      activeCases: 12,
      bio: "Experienced estate planning attorney with expertise in wills, trusts, and probate law. Dedicated to helping families secure their financial future.",
      avatar: "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=150&h=150&fit=crop&crop=face",
      joinDate: "2020-03-15",
      socialMedia: {
        linkedin: "https://linkedin.com/in/tristan",
        twitter: "https://twitter.com/tristan_law",
      },
      education: ["Harvard Law School - JD", "Yale University - BA Political Science"],
      certifications: ["Estate Planning Specialist", "Tax Law Certification"],
    },
    {
      id: "2",
      name: "Ms. Sophia",
      email: "sophia@dcase.com",
      phone: "+1 234 567 8902",
      specialization: "Employment Lawyer",
      experience: 10,
      rating: 4.9,
      activeCases: 15,
      bio: "Employment law specialist focusing on workplace rights, discrimination, and labor disputes. Passionate advocate for employee rights.",
      avatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&h=150&fit=crop&crop=face",
      joinDate: "2019-01-10",
      socialMedia: {
        linkedin: "https://linkedin.com/in/sophia-law",
        instagram: "https://instagram.com/sophia_legal",
      },
      education: ["Stanford Law School - JD", "UC Berkeley - BA Economics"],
      certifications: ["Employment Law Specialist", "Mediation Certification"],
    },
  ],
}
